fragment SiteParts on Site {
  __typename
  siteName
  communityName
  subtitle
  tagline
  logo
  heroImage
  location
  editionLabel
  heroLabel
  heroTitle
  heroText
  heroButtonText
  whatsappNumber
  primaryColor
  accentColor
  darkColor
  paperColor
}

fragment CategoriasParts on Categorias {
  __typename
  items {
    __typename
    name
    description
    color
    image
    featured
    order
  }
}

fragment NoticiasParts on Noticias {
  __typename
  items {
    __typename
    id
    category
    title
    summary
    author
    date
    featured
    image
    gallery
    attachments {
      __typename
      title
      description
      file
    }
    body
  }
}

fragment AvisosParts on Avisos {
  __typename
  items {
    __typename
    title
    text
  }
}

fragment DocumentosParts on Documentos {
  __typename
  items {
    __typename
    title
    description
    category
    date
    file
    featured
  }
}
