//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  noticias: Noticias;
  noticiasConnection: NoticiasConnection;
  avisos: Avisos;
  avisosConnection: AvisosConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNoticiasArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNoticiasConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NoticiasFilter>;
};


export type QueryAvisosArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAvisosConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AvisosFilter>;
};

export type DocumentFilter = {
  noticias?: InputMaybe<NoticiasFilter>;
  avisos?: InputMaybe<AvisosFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Noticias | Avisos | Folder;

export type NoticiasItems = {
  __typename?: 'NoticiasItems';
  id: Scalars['String']['output'];
  category: Scalars['String']['output'];
  title: Scalars['String']['output'];
  summary?: Maybe<Scalars['String']['output']>;
  author?: Maybe<Scalars['String']['output']>;
  date?: Maybe<Scalars['String']['output']>;
  featured?: Maybe<Scalars['Boolean']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
};

export type Noticias = Node & Document & {
  __typename?: 'Noticias';
  items?: Maybe<Array<Maybe<NoticiasItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type NoticiasItemsFilter = {
  id?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  summary?: InputMaybe<StringFilter>;
  author?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  featured?: InputMaybe<BooleanFilter>;
  image?: InputMaybe<ImageFilter>;
  body?: InputMaybe<StringFilter>;
};

export type NoticiasFilter = {
  items?: InputMaybe<NoticiasItemsFilter>;
};

export type NoticiasConnectionEdges = {
  __typename?: 'NoticiasConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Noticias>;
};

export type NoticiasConnection = Connection & {
  __typename?: 'NoticiasConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<NoticiasConnectionEdges>>>;
};

export type AvisosItems = {
  __typename?: 'AvisosItems';
  title: Scalars['String']['output'];
  text?: Maybe<Scalars['String']['output']>;
};

export type Avisos = Node & Document & {
  __typename?: 'Avisos';
  items?: Maybe<Array<Maybe<AvisosItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type AvisosItemsFilter = {
  title?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
};

export type AvisosFilter = {
  items?: InputMaybe<AvisosItemsFilter>;
};

export type AvisosConnectionEdges = {
  __typename?: 'AvisosConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Avisos>;
};

export type AvisosConnection = Connection & {
  __typename?: 'AvisosConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AvisosConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateNoticias: Noticias;
  createNoticias: Noticias;
  updateAvisos: Avisos;
  createAvisos: Avisos;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateNoticiasArgs = {
  relativePath: Scalars['String']['input'];
  params: NoticiasMutation;
};


export type MutationCreateNoticiasArgs = {
  relativePath: Scalars['String']['input'];
  params: NoticiasMutation;
};


export type MutationUpdateAvisosArgs = {
  relativePath: Scalars['String']['input'];
  params: AvisosMutation;
};


export type MutationCreateAvisosArgs = {
  relativePath: Scalars['String']['input'];
  params: AvisosMutation;
};

export type DocumentUpdateMutation = {
  noticias?: InputMaybe<NoticiasMutation>;
  avisos?: InputMaybe<AvisosMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  noticias?: InputMaybe<NoticiasMutation>;
  avisos?: InputMaybe<AvisosMutation>;
};

export type NoticiasItemsMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  summary?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
};

export type NoticiasMutation = {
  items?: InputMaybe<Array<InputMaybe<NoticiasItemsMutation>>>;
};

export type AvisosItemsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
};

export type AvisosMutation = {
  items?: InputMaybe<Array<InputMaybe<AvisosItemsMutation>>>;
};

export type NoticiasPartsFragment = { __typename: 'Noticias', items?: Array<{ __typename: 'NoticiasItems', id: string, category: string, title: string, summary?: string | null, author?: string | null, date?: string | null, featured?: boolean | null, image?: string | null, body?: string | null } | null> | null };

export type AvisosPartsFragment = { __typename: 'Avisos', items?: Array<{ __typename: 'AvisosItems', title: string, text?: string | null } | null> | null };

export type NoticiasQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type NoticiasQuery = { __typename?: 'Query', noticias: { __typename: 'Noticias', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'NoticiasItems', id: string, category: string, title: string, summary?: string | null, author?: string | null, date?: string | null, featured?: boolean | null, image?: string | null, body?: string | null } | null> | null } };

export type NoticiasConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NoticiasFilter>;
}>;


export type NoticiasConnectionQuery = { __typename?: 'Query', noticiasConnection: { __typename?: 'NoticiasConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'NoticiasConnectionEdges', cursor: string, node?: { __typename: 'Noticias', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'NoticiasItems', id: string, category: string, title: string, summary?: string | null, author?: string | null, date?: string | null, featured?: boolean | null, image?: string | null, body?: string | null } | null> | null } | null } | null> | null } };

export type AvisosQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AvisosQuery = { __typename?: 'Query', avisos: { __typename: 'Avisos', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'AvisosItems', title: string, text?: string | null } | null> | null } };

export type AvisosConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AvisosFilter>;
}>;


export type AvisosConnectionQuery = { __typename?: 'Query', avisosConnection: { __typename?: 'AvisosConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AvisosConnectionEdges', cursor: string, node?: { __typename: 'Avisos', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'AvisosItems', title: string, text?: string | null } | null> | null } | null } | null> | null } };

export const NoticiasPartsFragmentDoc = gql`
    fragment NoticiasParts on Noticias {
  __typename
  items {
    __typename
    id
    category
    title
    summary
    author
    date
    featured
    image
    body
  }
}
    `;
export const AvisosPartsFragmentDoc = gql`
    fragment AvisosParts on Avisos {
  __typename
  items {
    __typename
    title
    text
  }
}
    `;
export const NoticiasDocument = gql`
    query noticias($relativePath: String!) {
  noticias(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...NoticiasParts
  }
}
    ${NoticiasPartsFragmentDoc}`;
export const NoticiasConnectionDocument = gql`
    query noticiasConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: NoticiasFilter) {
  noticiasConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...NoticiasParts
      }
    }
  }
}
    ${NoticiasPartsFragmentDoc}`;
export const AvisosDocument = gql`
    query avisos($relativePath: String!) {
  avisos(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AvisosParts
  }
}
    ${AvisosPartsFragmentDoc}`;
export const AvisosConnectionDocument = gql`
    query avisosConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AvisosFilter) {
  avisosConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AvisosParts
      }
    }
  }
}
    ${AvisosPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      noticias(variables: NoticiasQueryVariables, options?: C): Promise<{data: NoticiasQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NoticiasQueryVariables, query: string}> {
        return requester<{data: NoticiasQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NoticiasQueryVariables, query: string}, NoticiasQueryVariables>(NoticiasDocument, variables, options);
      },
    noticiasConnection(variables?: NoticiasConnectionQueryVariables, options?: C): Promise<{data: NoticiasConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NoticiasConnectionQueryVariables, query: string}> {
        return requester<{data: NoticiasConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NoticiasConnectionQueryVariables, query: string}, NoticiasConnectionQueryVariables>(NoticiasConnectionDocument, variables, options);
      },
    avisos(variables: AvisosQueryVariables, options?: C): Promise<{data: AvisosQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AvisosQueryVariables, query: string}> {
        return requester<{data: AvisosQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AvisosQueryVariables, query: string}, AvisosQueryVariables>(AvisosDocument, variables, options);
      },
    avisosConnection(variables?: AvisosConnectionQueryVariables, options?: C): Promise<{data: AvisosConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AvisosConnectionQueryVariables, query: string}> {
        return requester<{data: AvisosConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AvisosConnectionQueryVariables, query: string}, AvisosConnectionQueryVariables>(AvisosConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  